/*
 * Copyright (c) 2019, 2020, 2021 SiKol Ltd.
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#ifndef SK_CONFIG_PARSER_PAIR_HXX_INCLUDED
#define SK_CONFIG_PARSER_PAIR_HXX_INCLUDED

#include <utility>

#include <sk/config/detail/parser/pair.hxx>
#include <sk/config/parser_for.hxx>

namespace sk::config {

    template <typename T1, typename T2>
    struct parser_for<std::pair<T1, T2>> {
        using parser_type =
            detail::parser::pair<typename parser_for<T1>::parser_type,
                                 typename parser_for<T2>::parser_type>;
        using rule_type = std::pair<T1, T2>;
        static constexpr char const name[] = "exactly two values";
    };

    namespace detail {

        // pair<T1,T2> <- pair<T1,T2>
        template <typename T1, typename T2>
        void propagate_value(auto & /*ctx*/, std::pair<T1, T2> &to,
                             std::pair<T1, T2> &from) {
            to = std::move(from);
        }

    } // namespace detail

} // namespace sk::config

#endif // SK_CONFIG_PARSER_PAIR_HXX_INCLUDED
