/*
 * Copyright (c) 2019, 2020, 2021 SiKol Ltd.
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#ifndef SK_CONFIG_DETAIL_MAKE_MEMBER_PARSER_HXX_INCLUDED
#define SK_CONFIG_DETAIL_MAKE_MEMBER_PARSER_HXX_INCLUDED

#include <list>
#include <set>
#include <vector>
#include <deque>
#include <unordered_set>

#include <boost/spirit/home/x3.hpp>

#include <sk/config/detail/propagate.hxx>
#include <sk/config/error.hxx>
#include <sk/config/parser/any_string.hxx>
#include <sk/config/parser/identifier.hxx>
#include <sk/config/parser/list.hxx>
#include <sk/config/parser/qstring.hxx>

namespace sk::config::detail {

    template <typename T> struct parser_for {
        // using parser = void;
    };

    template <> struct parser_for<std::string> {
        using parser = parser::any_string_parser<char>;
        static constexpr char const name[] = "a string";
    };

    template <> struct parser_for<std::wstring> {
        using parser = parser::any_string_parser<wchar_t>;
        static constexpr char const name[] = "a string";
    };

    template <> struct parser_for<short> {
        using parser = boost::spirit::x3::int_parser<short>;
        static constexpr char const name[] = "an integer";
    };

    template <> struct parser_for<unsigned short> {
        using parser = boost::spirit::x3::int_parser<unsigned short>;
        static constexpr char const name[] = "a positive integer";
    };

    template <> struct parser_for<unsigned int> {
        using parser = boost::spirit::x3::int_parser<unsigned int>;
        static constexpr char const name[] = "a positive integer";
    };

    template <> struct parser_for<int> {
        using parser = boost::spirit::x3::int_parser<int>;
        static constexpr char const name[] = "an integer";
    };

    template <> struct parser_for<long> {
        using parser = boost::spirit::x3::int_parser<long>;
        static constexpr char const name[] = "an integer";
    };

    template <> struct parser_for<unsigned long> {
        using parser = boost::spirit::x3::int_parser<unsigned long>;
        static constexpr char const name[] = "a positive integer";
    };

    template <> struct parser_for<long long> {
        using parser = boost::spirit::x3::int_parser<long long>;
        static constexpr char const name[] = "an integer";
    };

    template <> struct parser_for<unsigned long long> {
        using parser = boost::spirit::x3::int_parser<unsigned long long>;
        static constexpr char const name[] = "a positive integer";
    };

    template <typename T>
    struct config_real_policies : boost::spirit::x3::real_policies<T> {};

    template <> struct parser_for<float> {
        using parser =
            boost::spirit::x3::real_parser<float, config_real_policies<float>>;
        static constexpr char const name[] = "a decimal number";
    };

    template <> struct parser_for<double> {
        using parser =
            boost::spirit::x3::real_parser<double,
                                           config_real_policies<double>>;
        static constexpr char const name[] = "a decimal number";
    };

    template <> struct parser_for<long double> {
        using parser =
            boost::spirit::x3::real_parser<long double,
                                           config_real_policies<long double>>;
        static constexpr char const name[] = "a decimal number";
    };

    struct member_tag : parser_error_handler {};

    template <typename T, typename P> auto member_rule(const char *debug, P p) {
        namespace x3 = boost::spirit::x3;
        return x3::rule<member_tag, T>{debug} = p;
    };

    template <typename T, typename V>
    auto make_member_parser(V T::*const member) {
        namespace x3 = boost::spirit::x3;

        static typename parser_for<V>::parser parser;
        static auto rule = member_rule<V>(parser_for<V>::name, parser);

        return x3::expect[rule][propagate(member)];
    }

    template <typename T, typename V>
    auto make_member_parser(std::vector<V> T::*const member) {
        namespace x3 = boost::spirit::x3;

        using value_parser = typename parser_for<V>::parser;
        auto value_name = parser_for<V>::name;

        static parser::vector_parser<value_parser> parser;
        static auto rule = member_rule<std::vector<V>>(value_name, parser);

        return x3::expect[rule][propagate(member)];
    }

    template < typename T, typename V>
    auto make_member_parser(std::list<V> T::*const member) {
        namespace x3 = boost::spirit::x3;

        using value_parser = typename parser_for<V>::parser;
        auto value_name = parser_for<V>::name;

        static parser::vector_parser<value_parser> parser;
        static auto rule = member_rule<std::vector<V>>(value_name, parser);

        return x3::expect[rule][propagate(member)];
    }

    template <typename T, typename V>
    auto make_member_parser(std::deque<V> T::*const member) {
        namespace x3 = boost::spirit::x3;

        using value_parser = typename parser_for<V>::parser;
        auto value_name = parser_for<V>::name;

        static parser::vector_parser<value_parser> parser;
        static auto rule = member_rule<std::vector<V>>(value_name, parser);

        return x3::expect[rule][propagate(member)];
    }

    template <typename T, typename V>
    auto make_member_parser(std::unordered_set<V> T::*const member) {
        namespace x3 = boost::spirit::x3;

        using value_parser = typename parser_for<V>::parser;
        auto value_name = parser_for<V>::name;

        static parser::vector_parser<value_parser> parser;
        static auto rule = member_rule<std::vector<V>>(value_name, parser);

        return x3::expect[rule][propagate(member)];
    }

    template <typename T, typename V>
    auto make_member_parser(std::set<V> T::*const member) {
        namespace x3 = boost::spirit::x3;

        using value_parser = typename parser_for<V>::parser;
        auto value_name = parser_for<V>::name;

        static parser::vector_parser<value_parser> parser;
        static auto rule = member_rule<std::vector<V>>(value_name, parser);

        return x3::expect[rule][propagate(member)];
    }

} // namespace sk::config::detail

#endif // SK_CONFIG_DETAIL_MAKE_MEMBER_PARSER_HXX_INCLUDED
