/*
 * Copyright (c) 2019, 2020, 2021 SiKol Ltd.
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#ifndef SK_CONFIG_CONFIG_ERROR_HXX_INCLUDED
#define SK_CONFIG_CONFIG_ERROR_HXX_INCLUDED

#include <stdexcept>
#include <string>

#include <sk/config/location.hxx>

namespace sk::config {

    // A configuration error occured.
    struct error : std::runtime_error {
        error(std::string message) : std::runtime_error(std::move(message)) {}
    };

    // A configuration error occured and can be located in input.
    struct locatable_error : error {
        locatable_error(location const &loc, std::string message)
            : error(std::move(message)), _location(loc) {}

        auto get_location() const -> location {
            return _location;
        }

      private:
        config::location _location;
    };

    // An error occurred parsing the input.
    struct parse_error : locatable_error {
        parse_error(location const &loc, std::string message)
            : locatable_error(loc, std::move(message)) {}
    };

} // namespace sk::config

#endif // SK_CONFIG_CONFIG_ERROR_HXX_INCLUDED
